db.shipmentSequence.insert({'shipmentCode':'TP','shipmentType':'ToPay','startNumber':10000})
db.shipmentSequence.insert({'shipmentCode':'OA','shipmentType':'OnAccount','startNumber':10000})
db.shipmentSequence.insert({'shipmentCode':'F','shipmentType':'Free','startNumber':10000})
db.shipmentSequence.insert({'shipmentCode':'P','shipmentType':'Paid','startNumber':10000})
db.shipmentSequence.insert({'shipmentCode':'CT','shipmentType':'CounterTransaction','startNumber':10000})
