db.shipmentsequence.insert({'shipmentCode':'TP','shipmentType':'To Pay','startNumber':10000})
db.shipmentsequence.insert({'shipmentCode':'OA','shipmentType':'On-account','startNumber':10000})
db.shipmentsequence.insert({'shipmentCode':'F','shipmentType':'Free','startNumber':10000})
db.shipmentsequence.insert({'shipmentCode':'P','shipmentType':'Paid','startNumber':10000})
db.shipmentsequence.insert({'shipmentCode':'CT','shipmentType':'Counter Transaction','startNumber':10000})
